dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/vpp-sample-service

go:
  - 1.8.x

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - sudo apt-get install npm && npm install -g markdown-link-check
  - make install-tools

script:
- make check_links || true
- make all

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci