dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/vpp-sample-service

go:
  - 1.8.x

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - make install-tools

script:
- make all